@Basket_HostAddress = https://localhost:7282/basket

GET {{Basket_HostAddress}}/swn1
Accept: application/json

###

POST {{Basket_HostAddress}}
Content-Type: application/json
{
  "UserName": "swn1",
  "Items": [
    {
      "Quantity": 2,
      "Color": "Red",
      "Price": 0,
      "ProductId": "1",
      "ProductName": "Solar powered Flashlight"
    },
    {
      "Quantity": 1,
      "Color": "Blue",
      "Price":0,
      "ProductId": "2",
      "ProductName": "Hiking Poles"
    }
  ]
}

###

DELETE {{Basket_HostAddress}}/swn
Content-Type: application/json
