@Catalog_HostAddress = https://localhost:7050/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
  "id": 11,
  "name": "New New Product",
  "description": "This is a new product.",
  "price": 19.99,
  "imageUrl": "productnew.png"
}

###
PUT {{Catalog_HostAddress}}/2
Content-Type: application/json
{
  "id": 2,
  "name": "Updated New Product",
  "description": "This is an updated product.",
  "price": 24.99,
  "imageUrl": "productupdated.png"
}

###
DELETE {{Catalog_HostAddress}}/11
Content-Type: application/json
